routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('login');
});

Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('mlogin', 'Auth\LoginController@login')->name('mlogin');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['prefix' => 'messages'], function () {
    Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
    Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
    Route::get('create/{client_id}', ['as' => 'messages.client', 'uses' => 'MessagesController@client_create']);
    Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
    Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
    Route::put('{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
});

Route::get('powerpoint', 'ReportController@powerpoint')->name('powerpoint');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('profile/{user?}', 'UserController@profile')->name('profile');
Route::get('settings', 'UserController@settings')->name('settings');
Route::post('settings/password', 'UserController@handlePassword')->name('settings.password');
Route::post('settings/profile', 'UserController@handleProfile')->name('settings.profile');
Route::post('settings/notifications', 'UserController@handleNotifications')->name('settings.notifications');

Route::get('/', 'HomeController@index')->name('home');
Route::get('recents', 'HomeController@recents')->name('recents');
Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
Route::get('calendar', 'HomeController@calendar')->name('calendar');
Route::get('help', 'HelpController@create')->name('help.create');
Route::post('help', 'HelpController@store')->name('help.store');

Route::resource('emaillogs', 'EmailLogsController');
Route::get('emaillogs/{email_id}', 'EmailLogsController@show')->name('emaillogs.show');

Route::get('storage/crf', 'AssetController@getCrf')->name('crf_client');
Route::get('storage/avatar', 'AssetController@getAvatar')->name('avatar');
Route::get('storage/document', 'AssetController@getDocument')->name('document');
Route::get('storage/template', 'AssetController@getTemplate')->name('template');

Route::get('clients/amlreviewed', 'ClientController@amlReviewed')->name('clients.amlreviewed');
Route::get('clients/amlapproved', 'ClientController@amlApproved')->name('clients.amlapproved');
Route::get('clients/amlreviewedandapproved', 'ClientController@amlReviewedAndApproved')->name('clients.amlreviewedandapproved');
Route::get('clients/completed/{step_id}', 'ClientController@completed')->name('clients.completed');

Route::resource('clients', 'ClientController');
Route::get('clients/{client}/progress','ClientController@progress')->name('clients.progress');
Route::post('clients/{client}/progress','ClientController@storeProgress')->name('clients.storeprogress');
Route::post('clients/{client}/actions','ClientController@storeActions')->name('clients.storeactions');
Route::post('clients/{client}/progress/{process?}/{step?}','ClientController@completeStep')->name('clients.completestep');
Route::post('clients/{client}/progress2/{process?}/{step?}','ClientController@completeStep2')->name('clients.completestep2');
Route::get('clients/{client}/progress/{process}/{step}','ClientController@stepProgress')->name('clients.stepprogress');
Route::get('clients/{client}/progressaction/{step}/{action_id}','ClientController@stepProgressAction')->name('clients.stepprogressaction');
Route::get('clients/{client}/documents','ClientController@documents')->name('clients.documents');
Route::get('clients/{client}/forms','ClientController@forms')->name('clients.forms');
Route::get('clients/{client}/forms/uploadform','ClientController@uploadforms')->name('forms.uploadforms');
Route::get('clients/{client}/forms/editform/{formid}','ClientController@edituploadforms')->name('forms.editforms');
Route::post('clients/{client}/forms/storeform','ClientController@storeuploadforms')->name('forms.uploadstore');
Route::post('clients/{clientid}/forms/{formid}/formupdate','ClientController@updateuploadforms')->name('forms.formupdate');
Route::get('clients/{client}/forms/createcrf','ClientController@createCrfForm')->name('forms.createcrf');
Route::get('clients/{client}/forms/editcrf/{formid}','ClientController@editCrfForm')->name('forms.editcrf');
Route::get('clients/{client}/forms/signcrf/{formid}','ClientController@signCrfForm')->name('forms.signcrf');
Route::post('clients/{clientid}/forms/{formid}/updatecrf','ClientController@updateCrfForm')->name('forms.updatecrf');
Route::post('clients/{client}/forms/storecrf','ClientController@saveCrfForm')->name('forms.storecrf');
Route::get('clients/{client}/forms/{formid}/generatecrf','ClientController@generateCrfForm')->name('forms.generatecrf');
Route::get('clients/{client}/forms/upload','ClientController@saveCrfForm')->name('forms.upload');
Route::get('clients/{client}/forms/delete/{formid}','ClientController@deleteCrfForm')->name('crfforms.destroy');
Route::get('clients/{client_id}/completed/{step_id}/{newdate}','ClientController@complete')->name('clients.complete');
Route::get('clients/{client_id}/uncompleted/{step_id}','ClientController@uncomplete')->name('clients.uncomplete');
Route::get('clients/{client_id}/changecompleted/{step_id}/{newdate}','ClientController@changecomplete')->name('clients.changecomplete');
Route::post('clients/{client}/sendnotification/{activity?}','ClientController@sendNotification')->name('clients.sendnotification');
Route::post('clients/{client}/sendtemplate/{activity?}','ClientController@sendTemplate')->name('clients.sendtemplate');
Route::post('clients/{client}/senddocument/{activity?}','ClientController@sendDocument')->name('clients.senddocument');
Route::get('clients/{client}/viewtemplate/{template?}','ClientController@viewTemplate')->name('clients.viewtemplate');
Route::get('clients/{client}/viewdocument/{document?}','ClientController@viewDocument')->name('clients.viewdocument');
Route::put('clients/{client}/follow','ClientController@follow')->name('clients.follow');
Route::get('clients/{client}/activityprogress/{step}','ClientController@activityProgress')->name('clients.activityprogress');
Route::post('clients/{client}/storecomment','ClientController@storeComment')->name('clients.storecomment');
Route::post('clients/{client}/progressing','ClientController@storeProgressing')->name('clients.progressing');
Route::post('clients/{client}/approval','ClientController@approval')->name('clients.approval');
Route::post('clients/{client}/senddocuments/{activity?}','ClientController@sendDocuments')->name('clients.senddocuments');
Route::get('clients/{client}/delete','ClientController@destroy')->name('clients.delete');
Route::get('clients/show/{clientid}','ClientController@show')->name('clients.show');
Route::get('clients/{clientid}/restore','ClientController@restore')->name('clients.restore');
Route::post('clients/{clientid}/addcomment/{activityid}','ActivityCommentController@addComment');
Route::post('clients/{clientid}/showcomment/{activityid}','ActivityCommentController@showComment');
Route::post('clients/deletecomment/{commentid}','ActivityCommentController@destroyComment');
Route::post('clients/editcomment/{commentid}','ActivityCommentController@editComment');
Route::post('clients/updatecomment/{commentid}','ActivityCommentController@updateComment');

Route::get('clients/{client}/actions','ClientController@actions')->name('clients.actions');
Route::post('/clients/{client}/assignactivity','ActionsController@assignActivityToUser')->name('clients.assignactivity');
Route::get('/clients/getfirststep/{clientid}/{processid}','ProcessController@getProcessFirstStep');

Route::get('storeclientactivity/{token}','ClientController@createClientActivity')->name('clients.createclientactivity');
Route::post('storeclientactivity/{token}','ClientController@storeClientActivity')->name('clients.storeclientactivity');

Route::get('/clients/{clientid}/autocomplete_process/{processid}/{newprocess}','ClientController@autocompleteClientProcess');
Route::get('/clients/{clientid}/keep_process/{processid}/{newprocess}','ClientController@keepClientProcess');

Route::resource('referrers', 'ReferrerController');
Route::resource('documents', 'DocumentController');
Route::delete('documents/{id}/{client_id}', 'DocumentController@destroy')->name('documents.destroy');

Route::resource('templates', 'TemplateController');
Route::get('/templates/activities/{process_id}', 'TemplateController@getVars');

Route::get('roles', 'RoleController@index')->name('roles.index');
Route::get('roles/create', 'RoleController@create')->name('roles.create');
Route::post('roles', 'RoleController@store')->name('roles.store');
Route::put('roles', 'RoleController@update')->name('roles.update');
Route::delete('roles/{role?}', 'RoleController@destroy')->name('roles.destroy');

app/ClientForm.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class ClientForm extends Model
{
    protected $table = 'client_forms';
    protected $touches = ['client'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function type()
    {
        return pathinfo($this->file, PATHINFO_EXTENSION);
    }

    public function size()
    {
        try {
            $bytes = Storage::size('crf/' . $this->file);
            $i = floor(log($bytes, 1024));
            return round($bytes / pow(1024, $i), [0, 0, 2, 2, 3][$i]) . ['B', 'kB', 'MB', 'GB', 'TB'][$i];
        } catch (\Exception $e) {
            return "LStat";
        }
    }

    public function client()
    {
        return $this->belongsTo('App\Client','client_id');
    }
}

resources/views/clients/activityprogress.blade.php
@extends('clients.show')

@section('tab-content')
    <div class="col">
        <div class="process_step" id="activity_progress_{{$step->id}}">
            {{--<h3 id="{{$step->id}}" class="p-2" style="background-color: {{$client->process->getStageHex($step->name)}};width:100%;">{{$step->name}}</h3>--}}
            <h3 id="{{$step->id}}" class="p-2" style="width:100%;">{{$step->name}}</h3>
            <div style="padding: 0.5rem"><strong>Completed activities:</strong>
            <ul>
                {!! $completed !!}
            </ul>
                <strong>Not completed activities:</strong>
            <ul>
                {!! $not_completed !!}
            </ul>
            <a href="{{route('clients.progress', $client->id)}}/{{$step->id}}">Back to form</a></div>
        </div>
    </div>
@endsection
@section('extra-js')
    {{--<script>
        showActivityProgress({{$id}});
        
        function showActivityProgress(id){
            $("#activity_progress_"+id).show();
        }
    </script>--}}
@endsection

resources/views/clients/amlreports.blade.php
@extends('layouts.app')

@section('title') Clients @endsection

@section('header')
    <h1><i class="fa fa-address-card-o"></i> @yield('title')</h1>
    <a href="{{route('clients.create')}}" class="btn btn-outline-light float-right"><i class="fa fa-plus"></i> Client</a>
@endsection

@section('content')
    <form class="form-inline mt-3">
        Show &nbsp;
        {{Form::select('s',['all'=>'All','mine'=>'My','country'=>'Country wide','region'=>'Region wide','office'=>'Office wide'],old('selection'),['class'=>'form-control form-control-sm'])}}
        &nbsp; for &nbsp;
        {{Form::select('p',$processes ,old('p'),['class'=>'form-control form-control-sm'])}}
        &nbsp; for &nbsp;
        {{Form::select('c',['all'=>'All completions','no'=>'Not completed','yes'=>'Completed'],old('c'),['class'=>'form-control form-control-sm'])}}
        &nbsp; in &nbsp;
        {{Form::select('step',$steps ,old('step'),['class'=>'form-control form-control-sm'])}}
        &nbsp; from &nbsp;
        {{Form::date('f',old('f'),['class'=>'form-control form-control-sm'])}}
        &nbsp; to &nbsp;
        {{Form::date('t',old('t'),['class'=>'form-control form-control-sm'])}}
        &nbsp; matching &nbsp;
        <div class="input-group input-group-sm">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <i class="fa fa-search"></i>
                </div>
            </div>
            {{Form::text('q',old('query'),['class'=>'form-control form-control-sm','placeholder'=>'Search...'])}}
        </div>
        <button type="submit" class="btn btn-sm btn-secondary ml-2 mr-2"><i class="fa fa-search"></i> Search</button>
        <a href="{{route('clients.index')}}" class="btn btn-sm btn-outline-info"><i class="fa fa-eraser"></i> Clear</a>
    </form>

    <hr>

    <div class="table-responsive">
        <table class="table table-bordered table-sm table-hover">
            <thead class="thead-light">
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Contact</th>
                <th>Process</th>
                <th>Created</th>
                <th>Completed</th>
                <th><abbr title="Days taken to complete a clients process.">Duration</abbr></th>
                <th>Step</th>
                <th>User</th>
            </tr>
            </thead>
            <tbody>
            @forelse($clients as $client)
                <tr>
                    <td><a href="{{route('clients.show',$client)}}">{{$client->company}}</a></td>
                    <td>{{$client->email}}</td>
                    <td>{{$client->contact}}</td>
                    <td>{{$client->process->name}}</td>
                    <td>{{$client->created_at}}</td>
                    <td>{{!is_null($client->completed_at) ? $client->completed_at->toDateString() : ''}}</td>
                    <td>{{$client->completed_days}}</td>
                    <td>{{$client->getCurrentStep()->name}}</td>
                    <td><a href="{{route('profile',$client->introducer)}}" title="{{$client->introducer->name()}}"><img src="{{route('avatar',['q'=>$client->introducer->avatar])}}" class="blackboard-avatar blackboard-avatar-inline" alt="Avatar"/></a></td>
                </tr>
            @empty
                <tr>
                    <td colspan="100%" class="text-center"><small class="text-muted">No clients match those criteria.</small></td></td>
                </tr>
            @endforelse
            </tbody>

        </table>
    </div>

    <small class="text-muted">Found <b>{{sizeof($clients)}}</b> clients matching those criteria.</small>
@endsection

resources/views/clients/create.blade.php
@extends('adminlte.default')

@section('title') Capture Client @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <a href="{{route('clients.index')}}" class="btn btn-dark btn-sm float-right"><i class="fa fa-caret-left"></i> Back</a>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
    <div class="row mt-3 d-block d-md-none d-lg-none">
        <div class="col-sm-12">
            <div class="w-50 p-1 float-left">
            <a href="{{route('clients.create')}}" class="btn {{active('clients.create','active')}} btn-outline-dark w-100 float-left"><i class="fa fa-plus"></i> Client</a>
            </div>
            <div class="w-50 p-1 float-right">
            <a href="{{route('referrers.create')}}" class="btn btn-outline-dark btn-referrer w-100 float-right"><i class="fa fa-plus"></i> Referrer</a>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    {{Form::open(['url' => route('clients.store'), 'method' => 'post'])}}

    <div class="row mt-3">
        <div class="col-lg-12">
            <div class="form-group">
                {{Form::label('process', 'Process')}}
                {{Form::select('process',$processes,$last_process,['class'=>'form-control form-control-sm'. ($errors->has('process') ? ' is-invalid' : ''),'autofocus','id'=>'process'])}}
                @foreach($errors->get('process') as $error)
                    <div class="invalid-feedback">
                        {{$error}}
                    </div>
                @endforeach
            </div>

            <div class="form-group">
                {{Form::label('first_name', 'First Name')}}
                {{Form::text('first_name',old('first_name'),['class'=>'form-control form-control-sm'. ($errors->has('first_name') ? ' is-invalid' : ''),'placeholder'=>'First Name'])}}
                @foreach($errors->get('first_name') as $error)
                    <div class="invalid-feedback">
                        {{$error}}
                    </div>
                @endforeach
            </div>

            <div class="form-group">
                {{Form::label('last_name', 'Last Name')}}
                {{Form::text('last_name',old('last_name'),['class'=>'form-control form-control-sm'. ($errors->has('last_name') ? ' is-invalid' : ''),'placeholder'=>'Last Name'])}}
                @foreach($errors->get('last_name') as $error)
                    <div class="invalid-feedback">
                        {{$error}}
                    </div>
                @endforeach
            </div>

            <div class="form-group">
                {{Form::label('id_number', 'ID Number')}}
                {{Form::text('id_number',old('id_number'),['class'=>'form-control form-control-sm'. ($errors->has('id_number') ? ' is-invalid' : ''),'placeholder'=>'ID Number'])}}
                @foreach($errors->get('id_number') as $error)
                    <div class="invalid-feedback">
                        {{$error}}
                    </div>
                @endforeach
            </div>

            <div class="form-group">
                {{Form::label('company', 'Company Name')}}
                {{Form::text('company',old('company'),['class'=>'form-control form-control-sm'. ($errors->has('company') ? ' is-invalid' : ''),'placeholder'=>'Company name'])}}
                @foreach($errors->get('company') as $error)
                    <div class="invalid-feedback">
                        {{$error}}
                    </div>
                @endforeach
            </div>

            <div class="form-group">
                {{Form::label('company_registration_number', 'Company Registration Number')}}
                {{Form::text('company_registration_number',old('company_registration_number'),['class'=>'form-control form-control-sm'. ($errors->has('company_registration_number') ? ' is-invalid' : ''),'placeholder'=>'Company Registration Number'])}}
                @foreach($errors->get('company_registration_number') as $error)
                    <div class="invalid-feedback">
                        {{$error}}
                    </div>
                @endforeach
            </div>

            <div class="form-group">
                {{Form::label('cif_code', 'CIF Code')}}
                {{Form::text('cif_code',old('cif_code'),['class'=>'form-control form-control-sm'. ($errors->has('cif_code') ? ' is-invalid' : ''),'placeholder'=>'CIF Code'])}}
                @foreach($errors->get('cif_code') as $error)
                    <div class="invalid-feedback">
                        {{$error}}
                    </div>
                @endforeach
            </div>

            <div class="form-group">
                {{Form::label('email', 'Email')}}
                {{Form::email('email',old('email'),['class'=>'form-control form-control-sm'. ($errors->has('email') ? ' is-invalid' : ''),'placeholder'=>'Email'])}}
                @foreach($errors->get('email') as $error)
                    <div class="invalid-feedback">
                        {{$error}}
                    </div>
                @endforeach
            </div>

            <div class="form-group">
                {{Form::label('contact', 'Contact Number')}}
                {{Form::text('contact',old('contact'),['class'=>'form-control form-control-sm'. ($errors->has('contact') ? ' is-invalid' : ''),'placeholder'=>'Contact Number'])}}
                @foreach($errors->get('contact') as $error)
                    <div class="invalid-feedback">
                        {{$error}}
                    </div>
                @endforeach
            </div>
        </div>
    </div>


    <div class="form-group">
        <button type="submit" class="btn btn-sm add-client">Save</button>
    </div>

    {{Form::close()}}
    </div>
    <div class="modal fade" id="modalProcess" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header text-center" style="border-bottom: 0px;padding:.5rem;">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body mx-3">
                    <div class="row">
                        <div class="md-form col-sm-12 mb-3 text-left message">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('extra-js')
    <script>
        $(function(){
            $('#process').on('change',function(){
                $.ajax({
                    dataType: 'json',
                    url: '/processes/step_count/'+$('#process').val(),
                    type:'GET'
                }).done(function(data) {
                    if(data === 0){
                        let process = $('#process').val();
                        $('#modalProcess').modal('show');
                        $('#modalProcess').find('.message').html('The process you selected currently has no steps.<br /><br />' +
                            'Click <a href="/processes/' + process + '/show">here</a> to add steps to this process now.');
                        $('body').find('.add-client').prop('disabled',true);
                    } else {
                        $('body').find('.add-client').prop('disabled',false);
                    }
                });
            })
        })
    </script>
@endsection

resources/views/clients/documents.blade.php
@extends('clients.show')

@section('tab-content')
    <div class="col-lg-12">

        <a href="{{route('documents.create',['client'=>$client->id])}}" class="btn btn-outline-primary btn-sm"><i class="fa fa-plus"></i> Document</a>

        <div class="table-responsive mt-3">
            <table class="table table-bordered table-sm table-hover">
                <thead class="btn-dark">
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Size</th>
                    <th>Uploader</th>
                    <th>Added</th>
                    <th class="last">Action</th>
                </tr>
                </thead>
                <tbody>
                @forelse($client->documents as $document)
                    <tr>
                        <td><a href="{{route('document',['q'=>$document->file])}}" target="_blank">{{$document->name}}</a></td>
                        <td>{{$document->type()}}</td>
                        <td>{{$document->size()}}</td>
                        <td><a href="{{route('profile',$document->user)}}" title="{{$document->user->name()}}"><img src="{{route('avatar',['q'=>$document->user->avatar])}}" class="blackboard-avatar blackboard-avatar-inline" alt="{{$document->user->name()}}"/></a></td>
                        <td>{{$document->created_at->diffForHumans()}}</td>
                        <td class="last">
                            <a href="{{route('documents.edit',$document)}}" class="btn btn-success btn-sm">Edit</a>
                            {{ Form::open(['id' => 'documentDelete','method' => 'DELETE','route' => ['documents.destroy','id'=>$document->id,'client_id' =>$document->client_id],'style'=>'display:inline']) }}
                            <a href="#" class="delete deleteDoc btn btn-danger btn-sm">Delete</a>
                            {{Form::close() }}
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="100%" class="text-center">No documents match those criteria.</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/clients/index.blade.php
@extends('adminlte.default')

@section('title') Clients @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <a href="{{route('clients.create')}}" class="btn btn-dark btn-sm float-right"><i class="fa fa-plus"></i> Client</a>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
    <form class="form-inline mt-3">
        Show &nbsp;
        {{Form::select('s',['all'=>'All','mine'=>'My','country'=>'Country wide','region'=>'Region wide','office'=>'Office wide','deleted'=>'Deleted'],old('selection'),['class'=>'form-control form-control-sm'])}}
        &nbsp; for &nbsp;
        {{Form::select('p',$processes ,old('p'),['class'=>'form-control form-control-sm'])}}
        &nbsp; for &nbsp;
        {{Form::select('c',['all'=>'All completions','no'=>'Not converted','yes'=>'Converted','progress'=>'Progressing','noprogress'=>'Not progressing','approval'=>'Needs approval'],old('c'),['class'=>'form-control form-control-sm'])}}
        &nbsp; in &nbsp;
        {{Form::select('step',$steps ,old('step'),['class'=>'form-control form-control-sm'])}}
        &nbsp; from &nbsp;
        {{Form::date('f',old('f'),['class'=>'form-control form-control-sm'])}}
        &nbsp; to &nbsp;
        {{Form::date('t',old('t'),['class'=>'form-control form-control-sm'])}}
        &nbsp; matching &nbsp;
        <div class="input-group input-group-sm">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <i class="fa fa-search"></i>
                </div>
            </div>
            {{Form::text('q',old('query'),['class'=>'form-control form-control-sm','placeholder'=>'Search...'])}}
        </div>
        <button type="submit" class="btn btn-sm btn-secondary ml-2 mr-2"><i class="fa fa-search"></i> Search</button>
        <a href="{{route('clients.index')}}" class="btn btn-sm btn-info"><i class="fa fa-eraser"></i> Clear</a>
    </form>

    <hr>

    <div class="table-responsive">
        <table class="table table-bordered table-hover table-sm">
            <thead class="btn-dark">
            <tr>
                <th>@sortablelink('company', 'Name')</th>
                <th>@sortablelink('email', 'Email')</th>
                <th>@sortablelink('contact', 'Contact')</th>
                <th>@sortablelink('id_number', 'ID Number')</th>
                <th>@sortablelink('company_registration_number', 'Company Registration Number')</th>
                <th>@sortablelink('cif_code', 'CIF Code')</th>
                {{--<th>@sortablelink('process_id', 'Process')</th>--}}
                <th>@sortablelink('created', 'Created')</th>
                @if($np != 0)
                <th>@sortablelink('non_progressing', 'Non Progressing Date')</th>
                @endif
                <th>@sortablelink('completed', 'Completed')</th>
                <th><abbr title="Days taken to complete a clients process.">@sortablelink('process', 'Process')</abbr></th>
                <th>@sortablelink('step', 'Step')</th>
                {{--<th><abbr title="Is the client progressing or not."><i class="fa fa-tasks"></i></abbr></th>
                <th><abbr title="Does the client need approval."><i class="fa fa-tasks"></i></abbr></th>--}}
                <th>@sortablelink('introducer', 'User')</th>
            </tr>
            </thead>
            <tbody>
            @forelse($clients as $client)
                <tr>
                    <td><a href="{{route('clients.show',$client["id"])}}">{{($client["company"] == '' || $client["company"] == 'N/A' ?  : $client["company"] )}}</a></td>
                    <td>{{$client["email"]}}</td>
                    <td>{{$client["contact"]}}</td>
                    <td>{{$client["id_number"]}}</td>
                    <td>{{$client["company_registration_number"]}}</td>
                    <td>{{$client["cif_code"]}}</td>
                    {{--<td>{{$client["process"]}}</td>--}}
                    <td>{{$client["created_at"]}}</td>
                    @if($np != 0)
                        <td>{{$client["non_progressing"]}}</td>
                    @endif
                    <td>{{!is_null($client["completed_at"]) ? \Carbon\Carbon::parse($client["completed_at"])->format('Y-m-d') : ''}}</td>
                    <td>{{$client["process"]}}</td>
                    <td>{{$client["step"]}}</td>
                    {{--<td>{!!($client["is_progressing"]) ? '' : '<i class="fa fa-exclamation-triangle text-danger"></i>'!!}</td>
                    <td>{!!(!$client["needs_approval"]) ? '' : '<i class="fa fa-asterisk text-danger"></i>'!!}</td>--}}
                    <td><a href="{{route('profile',$client["introducer"])}}"><img src="{{route('avatar',['q'=>$client["avatar"] ])}}" class="blackboard-avatar blackboard-avatar-inline blackboard-avatar-navbar-img" alt="Avatar"/></a></td>
                </tr>
            @empty
                <tr>
                    <td colspan="100%" class="text-center"><small class="text-muted">No clients match those criteria.</small></td></td>
                </tr>
            @endforelse
            </tbody>

        </table>
    </div>

    <small class="text-muted">Found <b>{{count($clients)}}</b> clients matching those criteria.</small>
    </div>
@endsection