routes/web.php
    Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
    Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
    Route::get('create/{client_id}', ['as' => 'messages.client', 'uses' => 'MessagesController@client_create']);
    Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
    Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
    Route::put('{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
});

Route::get('powerpoint', 'ReportController@powerpoint')->name('powerpoint');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('profile/{user?}', 'UserController@profile')->name('profile');
Route::get('settings', 'UserController@settings')->name('settings');
Route::post('settings/password', 'UserController@handlePassword')->name('settings.password');
Route::post('settings/profile', 'UserController@handleProfile')->name('settings.profile');
Route::post('settings/notifications', 'UserController@handleNotifications')->name('settings.notifications');

Route::get('/', 'HomeController@index')->name('home');
Route::get('recents', 'HomeController@recents')->name('recents');
Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
Route::get('calendar', 'HomeController@calendar')->name('calendar');
Route::get('help', 'HelpController@create')->name('help.create');
Route::post('help', 'HelpController@store')->name('help.store');

Route::resource('emaillogs', 'EmailLogsController');
Route::get('emaillogs/{email_id}', 'EmailLogsController@show')->name('emaillogs.show');

Route::get('storage/crf', 'AssetController@getCrf')->name('crf_client');
Route::get('storage/avatar', 'AssetController@getAvatar')->name('avatar');
Route::get('storage/document', 'AssetController@getDocument')->name('document');
Route::get('storage/template', 'AssetController@getTemplate')->name('template');

Route::get('clients/amlreviewed', 'ClientController@amlReviewed')->name('clients.amlreviewed');
Route::get('clients/amlapproved', 'ClientController@amlApproved')->name('clients.amlapproved');
Route::get('clients/amlreviewedandapproved', 'ClientController@amlReviewedAndApproved')->name('clients.amlreviewedandapproved');
Route::get('clients/completed/{step_id}', 'ClientController@completed')->name('clients.completed');

Route::resource('clients', 'ClientController');
Route::get('clients/{client}/progress','ClientController@progress')->name('clients.progress');
Route::post('clients/{client}/progress','ClientController@storeProgress')->name('clients.storeprogress');
Route::post('clients/{client}/actions','ClientController@storeActions')->name('clients.storeactions');
Route::post('clients/{client}/progress/{process?}/{step?}','ClientController@completeStep')->name('clients.completestep');
Route::post('clients/{client}/progress2/{process?}/{step?}','ClientController@completeStep2')->name('clients.completestep2');
Route::get('clients/{client}/progress/{process}/{step}','ClientController@stepProgress')->name('clients.stepprogress');
Route::get('clients/{client}/progressaction/{step}/{action_id}','ClientController@stepProgressAction')->name('clients.stepprogressaction');
Route::get('clients/{client}/documents','ClientController@documents')->name('clients.documents');
Route::get('clients/{client}/forms','ClientController@forms')->name('clients.forms');
Route::get('clients/{client}/forms/uploadform','ClientController@uploadforms')->name('forms.uploadforms');
Route::get('clients/{client}/forms/editform/{formid}','ClientController@edituploadforms')->name('forms.editforms');
Route::post('clients/{client}/forms/storeform','ClientController@storeuploadforms')->name('forms.uploadstore');
Route::post('clients/{clientid}/forms/{formid}/formupdate','ClientController@updateuploadforms')->name('forms.formupdate');
Route::get('clients/{client}/forms/createcrf','ClientController@createCrfForm')->name('forms.createcrf');
Route::get('clients/{client}/forms/editcrf/{formid}','ClientController@editCrfForm')->name('forms.editcrf');
Route::get('clients/{client}/forms/signcrf/{formid}','ClientController@signCrfForm')->name('forms.signcrf');
Route::post('clients/{clientid}/forms/{formid}/updatecrf','ClientController@updateCrfForm')->name('forms.updatecrf');
Route::post('clients/{client}/forms/storecrf','ClientController@saveCrfForm')->name('forms.storecrf');
Route::get('clients/{client}/forms/{formid}/generatecrf','ClientController@generateCrfForm')->name('forms.generatecrf');
Route::get('clients/{client}/forms/upload','ClientController@saveCrfForm')->name('forms.upload');
Route::get('clients/{client}/forms/delete/{formid}','ClientController@deleteCrfForm')->name('crfforms.destroy');
Route::get('clients/{client_id}/completed/{step_id}/{newdate}','ClientController@complete')->name('clients.complete');
Route::get('clients/{client_id}/uncompleted/{step_id}','ClientController@uncomplete')->name('clients.uncomplete');
Route::get('clients/{client_id}/changecompleted/{step_id}/{newdate}','ClientController@changecomplete')->name('clients.changecomplete');
Route::post('clients/{client}/sendnotification/{activity?}','ClientController@sendNotification')->name('clients.sendnotification');
Route::post('clients/{client}/sendtemplate/{activity?}','ClientController@sendTemplate')->name('clients.sendtemplate');
Route::post('clients/{client}/senddocument/{activity?}','ClientController@sendDocument')->name('clients.senddocument');
Route::get('clients/{client}/viewtemplate/{template?}','ClientController@viewTemplate')->name('clients.viewtemplate');
Route::get('clients/{client}/viewdocument/{document?}','ClientController@viewDocument')->name('clients.viewdocument');
Route::put('clients/{client}/follow','ClientController@follow')->name('clients.follow');
Route::get('clients/{client}/activityprogress/{step}','ClientController@activityProgress')->name('clients.activityprogress');
Route::post('clients/{client}/storecomment','ClientController@storeComment')->name('clients.storecomment');
Route::post('clients/{client}/progressing','ClientController@storeProgressing')->name('clients.progressing');
Route::post('clients/{client}/approval','ClientController@approval')->name('clients.approval');
Route::post('clients/{client}/senddocuments/{activity?}','ClientController@sendDocuments')->name('clients.senddocuments');
Route::get('clients/{client}/delete','ClientController@destroy')->name('clients.delete');
Route::get('clients/show/{clientid}','ClientController@show')->name('clients.show');
Route::get('clients/{clientid}/restore','ClientController@restore')->name('clients.restore');
Route::post('clients/{clientid}/addcomment/{activityid}','ActivityCommentController@addComment');
Route::post('clients/{clientid}/showcomment/{activityid}','ActivityCommentController@showComment');
Route::post('clients/deletecomment/{commentid}','ActivityCommentController@destroyComment');
Route::post('clients/editcomment/{commentid}','ActivityCommentController@editComment');
Route::post('clients/updatecomment/{commentid}','ActivityCommentController@updateComment');

Route::get('clients/{client}/actions','ClientController@actions')->name('clients.actions');
Route::post('/clients/{client}/assignactivity','ActionsController@assignActivityToUser')->name('clients.assignactivity');
Route::get('/clients/getfirststep/{clientid}/{processid}','ProcessController@getProcessFirstStep');

Route::get('storeclientactivity/{token}','ClientController@createClientActivity')->name('clients.createclientactivity');
Route::post('storeclientactivity/{token}','ClientController@storeClientActivity')->name('clients.storeclientactivity');

Route::get('/clients/{clientid}/autocomplete_process/{processid}/{newprocess}','ClientController@autocompleteClientProcess');
Route::get('/clients/{clientid}/keep_process/{processid}/{newprocess}','ClientController@keepClientProcess');

Route::resource('referrers', 'ReferrerController');
Route::resource('documents', 'DocumentController');
Route::delete('documents/{id}/{client_id}', 'DocumentController@destroy')->name('documents.destroy');

Route::resource('templates', 'TemplateController');
Route::get('/templates/activities/{process_id}', 'TemplateController@getVars');

Route::get('roles', 'RoleController@index')->name('roles.index');
Route::get('roles/create', 'RoleController@create')->name('roles.create');
Route::post('roles', 'RoleController@store')->name('roles.store');
Route::put('roles', 'RoleController@update')->name('roles.update');
Route::delete('roles/{role?}', 'RoleController@destroy')->name('roles.destroy');

Route::resource('processes', 'ProcessController');
Route::get('processes/step_count/{process_id}', 'ProcessController@processStepCount');
Route::delete('processes/{process}/{processid}', 'ProcessController@destroy')->name('processes.destroy');
Route::get('processes/{process}/show', 'ProcessController@show')->name('processes.show');
Route::get('processes/{process}/steps/create', 'StepController@create')->name('steps.create');
Route::post('processes/{process}/steps/create', 'StepController@store')->name('steps.store');
Route::get('steps/{step}/edit', 'StepController@edit')->name('steps.edit');
Route::put('steps/{step}/edit', 'StepController@update')->name('steps.update');
Route::delete('steps/{step}', 'StepController@destroy')->name('steps.destroy');

app/Http/Controllers/ProcessController.php
<?php

namespace App\Http\Controllers;

use App\Office;
use App\Process;
use Illuminate\Http\Request;
use App\Step;

class ProcessController extends Controller
{
    public function __construct()
    {
        return $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $process_type_id = $request->has('t') ? $request->input('t') : 1;

        $processes = Process::with('office.area.region.division')->where('process_type_id', '=', $process_type_id);

        if ($request->has('q')) {
            $processes->where('name', 'LIKE', "%" . $request->input('q') . "%");
        }

        $parameters = [
            'processes' => $processes->get(),
            'type_name' => $process_type_id == 1 ? 'Processes' : 'Related Parties Structure',
            'processes' => $processes->get(),
            'process_type_id' => $process_type_id
        ];

        return view('processes.index')->with($parameters);
    }

    public function show(Process $process, Request $request)
    {
        $process->load('steps','office.area.region.division');

        $process_type_id = $request->has('t') ? $request->input('t'):1;

        return view('processes.show')->with(['process' => $process, 'process_type_id' => $process_type_id]);
    }

    public function create(Request $request)
    {
        $process_type_id = $request->has('t') ? $request->input('t') : 1;

        $parameters = [
            'offices' => Office::orderBy('name')->get()->pluck('name', 'id'),
            'type_name' => $process_type_id == 1 ? 'Processes' : 'Related Parties Structure',
            'process_type_id' => $process_type_id
        ];

        return view('processes.create')->with($parameters);
    }

    public function store(Request $request)
    {
        $process = new Process;
        $process->name = $request->input('name');
        $process->office_id = $request->input('office');
        $process->not_started_colour = str_replace('#', '', $request->input('not_started_colour'));
        $process->started_colour = str_replace('#', '', $request->input('started_colour'));
        $process->completed_colour = str_replace('#', '', $request->input('completed_colour'));
        $process->office_id = auth()->user()->office()->id;
        $process->process_type_id = $request->has('process_type_id') ? $request->input('process_type_id') : 1;
        $process->save();

        $type_name = $request->has('process_type_id') && $request->input('process_type_id') == 2 ? 'Related Parties Structure' : 'Process';

        return redirect(route('processes.show',$process))->with('flash_success', $type_name.' create successfully.');
    }

    public function edit(Process $process)
    {
        $paramaters = [
            'process' => $process,
            'offices' => Office::orderBy('name')->get()->pluck('name', 'id'),
        ];

        return view('processes.edit')->with($paramaters);
    }

    public function update(Process $process, Request $request)
    {
        $process->name = $request->input('name');
        $process->office_id = $request->input('office');
        $process->not_started_colour = str_replace('#', '', $request->input('not_started_colour'));
        $process->started_colour = str_replace('#', '', $request->input('started_colour'));
        $process->completed_colour = str_replace('#', '', $request->input('completed_colour'));
        $process->save();

        return redirect(route('processes.show',$process))->with('flash_success', 'Process updated successfully.');
    }

    public function destroy(Process $process, $processid, Request $request){

        if($process->clients->count()>0){

            return redirect(route('processes.show',$process))->with('flash_danger', 'There are still active clients assigned to that process.');
        }

        $process->destroy($processid);

        $process_type_id = $request->has('t') ? $request->input('t') : 1;
        $type_name = $process_type_id == 2 ? 'Related Parties Structure' : 'Process';

        return redirect(route('processes.index', ['t' => $process_type_id]))->with(['flash_success' => $type_name.'deleted successfully.']);
    }

    public function processStepCount($process_id){
        $count = Step::where('process_id',$process_id)->count();

        return response()->json($count);
    }

    public function getProcessFirstStep(Request $request, $clientid,$processid){

        $first_step = Step::where('process_id',$processid)->orderBy('order')->first();

        return response()->json($first_step->id);
    }
}

resources/views/processes/create.blade.php
@extends('adminlte.default')

@section('title') Create {{$type_name}} @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <a href="{{route('processes.index')}}" class="btn btn-dark btn-sm float-right"><i class="fa fa-caret-left"></i> Back</a>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
    {{Form::open(['url' => route('processes.store'), 'method' => 'post','class'=>'mt-3 mb-3','autocomplete' => 'off'])}}
    <input type="hidden" name="process_type_id" id="process_type_id" value="{{isset($process_type_id)?$process_type_id:1}}"/>
    {{Form::label('name', 'Name')}}
    {{Form::text('name',old('name'),['class'=>'form-control'. ($errors->has('name') ? ' is-invalid' : ''),'placeholder'=>'Name'])}}
    @foreach($errors->get('name') as $error)
        <div class="invalid-feedback">
            {{ $error }}
        </div>
    @endforeach

    {{Form::label('office', 'Office')}}
    {{Form::select('office',$offices,old('office'),['class'=>'form-control'. ($errors->has('office') ? ' is-invalid' : '')])}}
    @foreach($errors->get('office') as $error)
        <div class="invalid-feedback">
            {{ $error }}
        </div>
    @endforeach

    <div class="row mt-3">
        <div class="col-lg-4 text-center">
            <label><i class="fa fa-circle" style="color:rgba(242,99,91,.7)"></i> Not started</label>
            <div class="form-control">
                <input name="not_started_colour" type="text" style="background-color: rgba(242,99,91,.7)" value="rgba(242,99,91,.7)" class="not_started_color form-control form-control-sm" title="Stage colour: Not started"/>
            </div>
        </div>
        <div class="col-lg-4 text-center">
            <label><i class="fa fa-circle" style="color:rgba(252,182,61,.7)"></i> Started</label>
            <div class="form-control">
                <input name="started_colour" type="text" style="background-color: rgba(252,182,61,.7)" value="rgba(252,182,61,.7)" class="started_colour form-control form-control-sm" title="Stage colour: Started"/>
            </div>
        </div>
        <div class="col-lg-4 text-center">
            <label><i class="fa fa-circle" style="color:rgba(50,193,75,.7)"></i> Completed</label>
            <div class="form-control">
                <input name="completed_colour" type="text" style="background-color: rgba(50,193,75,.7)" value="rgba(50,193,75,.7)" class="completed_colour form-control form-control-sm" title="Stage colour: Completed"/>
            </div>
        </div>
    </div>

    <div class="blackboard-fab mr-3 mb-3">
        <button type="submit" class="btn btn-primary btn-lg"><i class="fa fa-save"></i> Save</button>
    </div>

    {{-- todo notifications --}}

    {{Form::close()}}
    </div>
@endsection
@section('extra-js')

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.3.3/css/bootstrap-colorpicker.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.3.3/js/bootstrap-colorpicker.min.js"></script>
    <style>
        .colorpicker-2x .colorpicker-saturation {
            width: 200px;
            height: 200px;
        }

        .colorpicker-2x .colorpicker-hue,
        .colorpicker-2x .colorpicker-alpha {
            width: 30px;
            height: 200px;
        }

        .colorpicker-2x .colorpicker-color,
        .colorpicker-2x .colorpicker-color div {
            height: 30px;
        }
    </style>
    <script>
        $(function () {
            // Basic instantiation:
            $('.not_started_color').colorpicker({
                align: 'center',
                input: $('.not_started_color2'),
                format: 'rgba',
                customClass: 'colorpicker-2x',
                sliders: {
                    saturation: {
                        maxLeft: 200,
                        maxTop: 200
                    },
                    hue: {
                        maxTop: 200
                    },
                    alpha: {
                        maxTop: 200
                    }
                }
            }).on('changeColor', function(event) {
                $('.not_started_color').css('background-color', event.color.toString());

            });

            $('.started_colour').colorpicker({
                align: 'center',
                format: 'rgba',
                customClass: 'colorpicker-2x',
                sliders: {
                    saturation: {
                        maxLeft: 200,
                        maxTop: 200
                    },
                    hue: {
                        maxTop: 200
                    },
                    alpha: {
                        maxTop: 200
                    }
                }
            }).on('changeColor', function(event) {
                $('.started_colour').css('background-color', event.color.toString());

            });

            $('.completed_colour').colorpicker({
                align: 'center',
                format: 'rgba',
                customClass: 'colorpicker-2x',
                sliders: {
                    saturation: {
                        maxLeft: 200,
                        maxTop: 200
                    },
                    hue: {
                        maxTop: 200
                    },
                    alpha: {
                        maxTop: 200
                    }
                }
            }).on('changeColor', function(event) {
                $('.completed_colour').css('background-color', event.color.toString());

            });
        });
    </script>
@endsection

resources/views/processes/edit.blade.php
@extends('adminlte.default')

@section('title') Edit process @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <a href="{{route('processes.show',$process)}}" class="btn btn-dark btn-sm float-right"><i class="fa fa-caret-left"></i> Back</a>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
    {{Form::open(['url' => route('processes.update',$process), 'method' => 'put','class'=>'mt-3 mb-3','autocomplete'=>'off'])}}

    {{Form::label('name', 'Name')}}
    {{Form::text('name',$process->name,['class'=>'form-control form-control-sm'. ($errors->has('name') ? ' is-invalid' : ''),'placeholder'=>'Name'])}}
    @foreach($errors->get('name') as $error)
        <div class="invalid-feedback">
            {{ $error }}
        </div>
    @endforeach

    {{Form::label('office', 'Office')}}
    {{Form::select('office',$offices,$process->office_id,['class'=>'form-control form-control-sm'. ($errors->has('office') ? ' is-invalid' : '')])}}
    @foreach($errors->get('office') as $error)
        <div class="invalid-feedback">
            {{ $error }}
        </div>
    @endforeach

    <div class="row mt-3">
        <div class="col-lg-4 text-center">
            <label><i class="fa fa-circle" style="color: {{$process->getStageHex(0)}}"></i> Not started</label>
            <div class="form-control">
                <input name="not_started_colour" type="text" style="background-color:{{$process->getStageHex(0, false)}};" class="not_started_color form-control form-control-sm"  value="{{$process->getStageHex(1, false)}}" title="Stage colour: Not started"/>
            </div>
        </div>
        <div class="col-lg-4 text-center">
            <label><i class="fa fa-circle" style="color: {{$process->getStageHex(1)}}"></i> Started</label>
            <div class="form-control">
                <input name="started_colour" type="text"  style="background-color:{{$process->getStageHex(1, false)}};" class="started_colour form-control form-control-sm" value="{{$process->getStageHex(1, false)}}" title="Stage colour: Started"/>
            </div>
        </div>
        <div class="col-lg-4 text-center">
            <label><i class="fa fa-circle" style="color: {{$process->getStageHex(2)}}"></i> Completed</label>
            <div class="form-control">
                <input name="completed_colour" type="text" style="background-color:{{$process->getStageHex(2, false)}};" class="completed_colour form-control form-control-sm" value="{{$process->getStageHex(2,false)}}" title="Stage colour: Completed"/>
            </div>
        </div>
    </div>

    <div class="blackboard-fab mr-3 mb-3">
        <button type="submit" class="btn btn-primary btn-lg"><i class="fa fa-save"></i> Save</button>
    </div>


    {{-- todo notifications --}}

    {{Form::close()}}
    </div>
@endsection
@section('extra-js')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.3.3/css/bootstrap-colorpicker.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.3.3/js/bootstrap-colorpicker.min.js"></script>
    <style>
        .colorpicker-2x .colorpicker-saturation {
            width: 200px;
            height: 200px;
        }

        .colorpicker-2x .colorpicker-hue,
        .colorpicker-2x .colorpicker-alpha {
            width: 30px;
            height: 200px;
        }

        .colorpicker-2x .colorpicker-color,
        .colorpicker-2x .colorpicker-color div {
            height: 30px;
        }
    </style>
    <script>
        $(function () {
            // Basic instantiation:
            $('.not_started_color').colorpicker({
                align: 'center',
                format: 'rgba',
                customClass: 'colorpicker-2x',
                sliders: {
                    saturation: {
                        maxLeft: 200,
                        maxTop: 200
                    },
                    hue: {
                        maxTop: 200
                    },
                    alpha: {
                        maxTop: 200
                    }
                }
            }).on('changeColor', function(event) {
                $('.not_started_color').css('background-color', event.color.toString());

            });

            $('.started_colour').colorpicker({
                align: 'center',
                format: 'rgba',
                customClass: 'colorpicker-2x',
                sliders: {
                    saturation: {
                        maxLeft: 200,
                        maxTop: 200
                    },
                    hue: {
                        maxTop: 200
                    },
                    alpha: {
                        maxTop: 200
                    }
                }
            }).on('changeColor', function(event) {
                $('.started_colour').css('background-color', event.color.toString());

            });

            $('.completed_colour').colorpicker({
                align: 'center',
                format: 'rgba',
                customClass: 'colorpicker-2x',
                sliders: {
                    saturation: {
                        maxLeft: 200,
                        maxTop: 200
                    },
                    hue: {
                        maxTop: 200
                    },
                    alpha: {
                        maxTop: 200
                    }
                }
            }).on('changeColor', function(event) {
                $('.completed_colour').css('background-color', event.color.toString());

            });
        });
    </script>
@endsection

resources/views/processes/index.blade.php
@extends('adminlte.default')

@section('title') {{$type_name}} @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <a href="{{route('processes.create')}}?t={{$process_type_id}}" class="btn btn-dark btn-sm float-right"><i class="fa fa-plus"></i> {{$type_name}}</a>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
    <form class="form-inline mt-3">
        Show &nbsp;
        {{Form::select('s',['all'=>'All','mine'=>'My','company'=>'Branch'],old('selection'),['class'=>'form-control form-control-sm'])}}
        &nbsp; of &nbsp;
        {{Form::select('p',['all'=>'All Time','week'=>'Last Week','month'=>'Last Month','year'=>'Last Year'],old('period'),['class'=>'form-control form-control-sm'])}}
        &nbsp; matching &nbsp;
        <div class="input-group input-group-sm">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <i class="fa fa-search"></i>
                </div>
            </div>
            {{Form::text('q',old('query'),['class'=>'form-control form-control-sm','placeholder'=>'Search...'])}}
        </div>
        <button type="submit" class="btn btn-sm btn-secondary ml-2 mr-2"><i class="fa fa-search"></i> Search</button>
        <a href="{{route('processes.index')}}" class="btn btn-sm btn-info"><i class="fa fa-eraser"></i> Clear</a>
    </form>

    <hr>

    <div class="table-responsive">
        <table class="table table-bordered table-sm table-hover">
            <thead class="btn-dark">
            <tr>
                <th>Name</th>
                <th>Division</th>
                <th>Region</th>
                <th>Area</th>
                <th>Office</th>
                <th>Created</th>
                <th>Modified</th>
                <th class="last">Actions</th>
            </tr>
            </thead>
            <tbody>
            @forelse($processes as $process)
                <tr>
                    <td>{{$process->name}}</td>
                    <td>{{$process->office->area->region->division->name}}</td>
                    <td>{{$process->office->area->region->name}}</td>
                    <td>{{$process->office->area->name}}</td>
                    <td>{{$process->office->name}}</td>
                    <td>{{$process->created_at->diffForHumans()}}</td>
                    <td>{{$process->updated_at->diffForHumans()}}</td>
                    <td class="last">
                        <a href="{{route('processes.show',$process)}}?t={{$process_type_id}}" class="btn btn-info btn-sm">View</a>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="100%" class="text-center"><small class="text-muted">No {{$type_name}} match those criteria.</small></td>
                </tr>
            @endforelse
            </tbody>
        </table>
    </div>
    </div>
@endsection