routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('login');
});

Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('mlogin', 'Auth\LoginController@login')->name('mlogin');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['prefix' => 'messages'], function () {
    Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
    Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
    Route::get('create/{client_id}', ['as' => 'messages.client', 'uses' => 'MessagesController@client_create']);
    Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
    Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
    Route::put('{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
});

Route::get('powerpoint', 'ReportController@powerpoint')->name('powerpoint');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('profile/{user?}', 'UserController@profile')->name('profile');
Route::get('settings', 'UserController@settings')->name('settings');
Route::post('settings/password', 'UserController@handlePassword')->name('settings.password');
Route::post('settings/profile', 'UserController@handleProfile')->name('settings.profile');
Route::post('settings/notifications', 'UserController@handleNotifications')->name('settings.notifications');

Route::get('/', 'HomeController@index')->name('home');
Route::get('recents', 'HomeController@recents')->name('recents');
Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
Route::get('calendar', 'HomeController@calendar')->name('calendar');
Route::get('help', 'HelpController@create')->name('help.create');
Route::post('help', 'HelpController@store')->name('help.store');

Route::resource('emaillogs', 'EmailLogsController');
Route::get('emaillogs/{email_id}', 'EmailLogsController@show')->name('emaillogs.show');

Route::get('storage/crf', 'AssetController@getCrf')->name('crf_client');
Route::get('storage/avatar', 'AssetController@getAvatar')->name('avatar');
Route::get('storage/document', 'AssetController@getDocument')->name('document');
Route::get('storage/template', 'AssetController@getTemplate')->name('template');

Route::get('clients/amlreviewed', 'ClientController@amlReviewed')->name('clients.amlreviewed');
Route::get('clients/amlapproved', 'ClientController@amlApproved')->name('clients.amlapproved');
Route::get('clients/amlreviewedandapproved', 'ClientController@amlReviewedAndApproved')->name('clients.amlreviewedandapproved');
Route::get('clients/completed/{step_id}', 'ClientController@completed')->name('clients.completed');

Route::resource('clients', 'ClientController');
Route::get('clients/{client}/progress','ClientController@progress')->name('clients.progress');
Route::post('clients/{client}/progress','ClientController@storeProgress')->name('clients.storeprogress');
Route::post('clients/{client}/actions','ClientController@storeActions')->name('clients.storeactions');
Route::post('clients/{client}/progress/{process?}/{step?}','ClientController@completeStep')->name('clients.completestep');
Route::post('clients/{client}/progress2/{process?}/{step?}','ClientController@completeStep2')->name('clients.completestep2');
Route::get('clients/{client}/progress/{process}/{step}','ClientController@stepProgress')->name('clients.stepprogress');
Route::get('clients/{client}/progressaction/{step}/{action_id}','ClientController@stepProgressAction')->name('clients.stepprogressaction');
Route::get('clients/{client}/documents','ClientController@documents')->name('clients.documents');
Route::get('clients/{client}/forms','ClientController@forms')->name('clients.forms');
Route::get('clients/{client}/forms/uploadform','ClientController@uploadforms')->name('forms.uploadforms');
Route::get('clients/{client}/forms/editform/{formid}','ClientController@edituploadforms')->name('forms.editforms');
Route::post('clients/{client}/forms/storeform','ClientController@storeuploadforms')->name('forms.uploadstore');
Route::post('clients/{clientid}/forms/{formid}/formupdate','ClientController@updateuploadforms')->name('forms.formupdate');
Route::get('clients/{client}/forms/createcrf','ClientController@createCrfForm')->name('forms.createcrf');
Route::get('clients/{client}/forms/editcrf/{formid}','ClientController@editCrfForm')->name('forms.editcrf');
Route::get('clients/{client}/forms/signcrf/{formid}','ClientController@signCrfForm')->name('forms.signcrf');
Route::post('clients/{clientid}/forms/{formid}/updatecrf','ClientController@updateCrfForm')->name('forms.updatecrf');
Route::post('clients/{client}/forms/storecrf','ClientController@saveCrfForm')->name('forms.storecrf');
Route::get('clients/{client}/forms/{formid}/generatecrf','ClientController@generateCrfForm')->name('forms.generatecrf');
Route::get('clients/{client}/forms/upload','ClientController@saveCrfForm')->name('forms.upload');
Route::get('clients/{client}/forms/delete/{formid}','ClientController@deleteCrfForm')->name('crfforms.destroy');
Route::get('clients/{client_id}/completed/{step_id}/{newdate}','ClientController@complete')->name('clients.complete');
Route::get('clients/{client_id}/uncompleted/{step_id}','ClientController@uncomplete')->name('clients.uncomplete');
Route::get('clients/{client_id}/changecompleted/{step_id}/{newdate}','ClientController@changecomplete')->name('clients.changecomplete');
Route::post('clients/{client}/sendnotification/{activity?}','ClientController@sendNotification')->name('clients.sendnotification');
Route::post('clients/{client}/sendtemplate/{activity?}','ClientController@sendTemplate')->name('clients.sendtemplate');
Route::post('clients/{client}/senddocument/{activity?}','ClientController@sendDocument')->name('clients.senddocument');
Route::get('clients/{client}/viewtemplate/{template?}','ClientController@viewTemplate')->name('clients.viewtemplate');
Route::get('clients/{client}/viewdocument/{document?}','ClientController@viewDocument')->name('clients.viewdocument');
Route::put('clients/{client}/follow','ClientController@follow')->name('clients.follow');
Route::get('clients/{client}/activityprogress/{step}','ClientController@activityProgress')->name('clients.activityprogress');
Route::post('clients/{client}/storecomment','ClientController@storeComment')->name('clients.storecomment');
Route::post('clients/{client}/progressing','ClientController@storeProgressing')->name('clients.progressing');
Route::post('clients/{client}/approval','ClientController@approval')->name('clients.approval');
Route::post('clients/{client}/senddocuments/{activity?}','ClientController@sendDocuments')->name('clients.senddocuments');
Route::get('clients/{client}/delete','ClientController@destroy')->name('clients.delete');
Route::get('clients/show/{clientid}','ClientController@show')->name('clients.show');
Route::get('clients/{clientid}/restore','ClientController@restore')->name('clients.restore');
Route::post('clients/{clientid}/addcomment/{activityid}','ActivityCommentController@addComment');
Route::post('clients/{clientid}/showcomment/{activityid}','ActivityCommentController@showComment');
Route::post('clients/deletecomment/{commentid}','ActivityCommentController@destroyComment');
Route::post('clients/editcomment/{commentid}','ActivityCommentController@editComment');
Route::post('clients/updatecomment/{commentid}','ActivityCommentController@updateComment');

Route::get('clients/{client}/actions','ClientController@actions')->name('clients.actions');
Route::post('/clients/{client}/assignactivity','ActionsController@assignActivityToUser')->name('clients.assignactivity');
Route::get('/clients/getfirststep/{clientid}/{processid}','ProcessController@getProcessFirstStep');

Route::get('storeclientactivity/{token}','ClientController@createClientActivity')->name('clients.createclientactivity');
Route::post('storeclientactivity/{token}','ClientController@storeClientActivity')->name('clients.storeclientactivity');

Route::get('/clients/{clientid}/autocomplete_process/{processid}/{newprocess}','ClientController@autocompleteClientProcess');
Route::get('/clients/{clientid}/keep_process/{processid}/{newprocess}','ClientController@keepClientProcess');

Route::resource('referrers', 'ReferrerController');
Route::resource('documents', 'DocumentController');
Route::delete('documents/{id}/{client_id}', 'DocumentController@destroy')->name('documents.destroy');

Route::resource('templates', 'TemplateController');
Route::get('/templates/activities/{process_id}', 'TemplateController@getVars');

Route::get('roles', 'RoleController@index')->name('roles.index');
Route::get('roles/create', 'RoleController@create')->name('roles.create');
Route::post('roles', 'RoleController@store')->name('roles.store');
Route::put('roles', 'RoleController@update')->name('roles.update');
Route::delete('roles/{role?}', 'RoleController@destroy')->name('roles.destroy');

resources/views/templates/create.blade.php
@extends('adminlte.default')

@section('title') Upload Template @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <a href="{{route('templates.index')}}" class="btn btn-dark btn-sm float-right"><i class="fa fa-caret-left"></i> Back</a>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
        <hr />
    {{Form::open(['url' => route('templates.store'), 'method' => 'post','files'=>true])}}

    <div class="form-group mt-3">
        {{Form::label('name', 'Name')}}
        {{Form::text('name',old('name'),['class'=>'form-control form-control-sm'. ($errors->has('name') ? ' is-invalid' : ''),'placeholder'=>'Name'])}}
        @foreach($errors->get('name') as $error)
            <div class="invalid-feedback">
                {{ $error }}
            </div>
        @endforeach
    </div>

    <div class="form-group">
        {{Form::label('process', 'Process / Related Party Structure')}}
        {{Form::select('process',$process,old('process'),['class'=>'form-control form-control-sm'. ($errors->has('process') ? ' is-invalid' : ''),'id'=>'process'])}}
        @foreach($errors->get('process') as $error)
            <div class="invalid-feedback">
                {{ $error }}
            </div>
        @endforeach
    </div>

    <div class="form-group">
        {{Form::label('file', 'Template File')}}
        {{Form::file('file',['class'=>'form-control form-control-sm'. ($errors->has('file') ? ' is-invalid' : ''),'placeholder'=>'File'])}}
        @foreach($errors->get('file') as $error)
            <div class="invalid-feedback">
                {{ $error }}
            </div>
        @endforeach
    </div>

    <div class="form-group">
        {{Form::label('file', 'Variables')}}
        <div class="row col-sm-12 table-responsive" v-pre>
            <table class="table table-fixed">
                <thead>
                    <tr>
                        <th class="col-sm-4">Step</th>
                        <th class="col-sm-4">Activity Name</th>
                        <th class="col-sm-4">Variable</th>
                    </tr>
                </thead>
                <tbody id="template_vars" class="loader" style="height: 300px;overflow-y: auto;display:block;overflow-x: hidden;">
                    <tr>
                        <td colspan="3" class="col-sm-12">
                            <div class="alert alert-info col-sm-12">Please select a process to populate available variables for template generation.</div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="blackboard-fab mr-3 mb-3">
        <button type="submit" class="btn btn-info btn-lg"><i class="fa fa-save"></i><span style="font-size:1rem;line-height: 1.8;padding-left:10px;float: right;display:block;text-align:left;">Save</span></button>
    </div>

    {{Form::close()}}
    </div>
@endsection
@section('extra-css')
    <style>

        .table-fixed {
            width: 100%;
        }
        .table-fixed tbody {
            height: 200px;
            overflow-y: auto;
            width: 100%;
        }
        .table-fixed thead, .table-fixed tbody, .table-fixed tr, .table-fixed td, .table-fixed th {
            display: block;
        }
        .table-fixed tbody td {
            float: left;
        }
        .table-fixed thead tr th {
            float: left;
        }
    </style>
@endsection
@section('extra-js')
    <script>
        $(function(){

            if($('#process').val() != '0') {
                getVars($('#process').val());
            }

            $('#process').on('change',function(){
               let process_id = $('#process').val();

                getVars(process_id);
            });
        })

        function getVars(process_id){
            var spinner = '<svg version="1.1" id="loader-1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"\n' +
                '     width="40px" height="40px" preserveAspectRatio="xMaxYMax meet" viewBox="0 0 50 50" style="enable-background:new 0 0 50 50;">\n' +
                '  <path fill="#fff" d="M43.935,25.145c0-10.318-8.364-18.683-18.683-18.683c-10.318,0-18.683,8.365-18.683,18.683h4.068c0-8.071,6.543-14.615,14.615-14.615c8.072,0,14.615,6.543,14.615,14.615H43.935z">\n' +
                '    <animateTransform attributeType="xml"\n' +
                '      attributeName="transform"\n' +
                '      type="rotate"\n' +
                '      from="0 25 25"\n' +
                '      to="360 25 25"\n' +
                '      dur="1s"\n' +
                '      repeatCount="indefinite"/>\n' +
                '    </path>\n' +
                '  </svg>';

            $.ajax({
                url: '/templates/activities/' + process_id,
                type: "GET",
                dataType: "json",
                beforeSend: function () {
                    $('.loader').html('<tr><td colspan="3" class="col-sm-12">' + spinner + '</td></tr>');
                },
                success: function (data) {
                    let rows = '<tr>';
                    let count = 0;
                    $.each(data, function (key, value) {
                        count++;
                        rows = rows + '<td class="col-sm-4">' + value.step + '</td>';
                        rows = rows + '<td class="col-sm-4">' + value.name + '</td>';
                        rows = rows + '<td class="col-sm-4">$&#123;' + value.variable + '&#125;</td>';
                        if (count === 1) {
                            rows = rows + '</tr><tr>';
                            count = 0;
                        }
                    });

                    $("#template_vars").html(rows);
                }
            });
        }
    </script>
@endsection

resources/views/templates/edit.blade.php
@extends('adminlte.default')

@section('title') Edit Template @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <a href="{{route('templates.index')}}" class="btn btn-dark btn-sm float-right"><i class="fa fa-caret-left"></i> Back</a>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
        <hr />
    {{Form::open(['url' => route('templates.update',$template), 'method' => 'put','files'=>true])}}

    <div class="form-group mt-3">
        {{Form::label('name', 'Name')}}
        {{Form::text('name',$template->name,['class'=>'form-control form-control-sm'. ($errors->has('name') ? ' is-invalid' : ''),'placeholder'=>'Name'])}}
        @foreach($errors->get('name') as $error)
            <div class="invalid-feedback">
                {{ $error }}
            </div>
        @endforeach
    </div>

    <div class="form-group">
        {{Form::label('process', 'Process / Related Party Structure')}}
        {{Form::select('process',$process,$template->process_id,['class'=>'form-control form-control-sm'. ($errors->has('process') ? ' is-invalid' : ''),'id'=>'process'])}}
        @foreach($errors->get('process') as $error)
            <div class="invalid-feedback">
                {{ $error }}
            </div>
        @endforeach
    </div>

    <div class="form-group">
        {{Form::label('file', 'Template File')}}
        {{Form::file('file',['class'=>'form-control form-control-sm'. ($errors->has('file') ? ' is-invalid' : ''),'placeholder'=>'File'])}}
        @foreach($errors->get('file') as $error)
            <div class="invalid-feedback">
                {{ $error }}
            </div>
        @endforeach
        <small>
            Leave empty to keep <a href="{{route('template',['q'=>$template->file])}}" target="_blank" download="{{$template->name}}.{{$template->type()}}">previous file</a>
        </small>
    </div>

        <div class="form-group">
            {{Form::label('file', 'Variables')}}
            <div class="row col-sm-12 table-responsive" v-pre>
                <table class="table table-fixed">
                    <thead>
                    <tr>
                        <th class="col-sm-4">Step</th>
                        <th class="col-sm-4">Activity Name</th>
                        <th class="col-sm-4">Variable</th>
                    </tr>
                    </thead>
                    <tbody id="template_vars" class="loader" style="height: 300px;overflow-y: auto;display:block;overflow-x: hidden;">
                    <tr>
                        <td colspan="3" class="col-sm-12">
                            <div class="alert alert-info col-sm-12">Please select a process to populate available variables for template generation.</div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="blackboard-fab mr-3 mb-3">
            <button type="submit" class="btn btn-info btn-lg"><i class="fa fa-save"></i><span style="font-size:1rem;line-height: 1.8;padding-left:10px;float: right;display:block;text-align:left;">Save</span></button>
        </div>

    {{Form::close()}}
    </div>
@endsection
@section('extra-css')
    <style>

        .table-fixed {
            width: 100%;
        }
        .table-fixed tbody {
            height: 200px;
            overflow-y: auto;
            width: 100%;
        }
        .table-fixed thead, .table-fixed tbody, .table-fixed tr, .table-fixed td, .table-fixed th {
            display: block;
        }
        .table-fixed tbody td {
            float: left;
        }
        .table-fixed thead tr th {
            float: left;
        }
    </style>
@endsection
@section('extra-js')
    <script>
        $(function(){

            if($('#process').val() != '0') {
                getVars($('#process').val());
            }

            $('#process').on('change',function(){
                let process_id = $('#process').val();

                getVars(process_id);
            });
        })

        function getVars(process_id){
            var spinner = '<svg version="1.1" id="loader-1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"\n' +
                '     width="40px" height="40px" preserveAspectRatio="xMaxYMax meet" viewBox="0 0 50 50" style="enable-background:new 0 0 50 50;">\n' +
                '  <path fill="#fff" d="M43.935,25.145c0-10.318-8.364-18.683-18.683-18.683c-10.318,0-18.683,8.365-18.683,18.683h4.068c0-8.071,6.543-14.615,14.615-14.615c8.072,0,14.615,6.543,14.615,14.615H43.935z">\n' +
                '    <animateTransform attributeType="xml"\n' +
                '      attributeName="transform"\n' +
                '      type="rotate"\n' +
                '      from="0 25 25"\n' +
                '      to="360 25 25"\n' +
                '      dur="1s"\n' +
                '      repeatCount="indefinite"/>\n' +
                '    </path>\n' +
                '  </svg>';

            $.ajax({
                url: '/templates/activities/' + process_id,
                type: "GET",
                dataType: "json",
                beforeSend: function () {
                    $('.loader').html('<tr><td colspan="3" class="col-sm-12">' + spinner + '</td></tr>');
                },
                success: function (data) {
                    let rows = '<tr>';
                    let count = 0;
                    $.each(data, function (key, value) {
                        count++;
                        rows = rows + '<td class="col-sm-4">' + value.step + '</td>';
                        rows = rows + '<td class="col-sm-4">' + value.name + '</td>';
                        rows = rows + '<td class="col-sm-4">$&#123;' + value.variable + '&#125;</td>';
                        if (count === 1) {
                            rows = rows + '</tr><tr>';
                            count = 0;
                        }
                    });

                    $("#template_vars").html(rows);
                }
            });
        }
    </script>
@endsection

resources/views/templates/index.blade.php
@extends('adminlte.default')

@section('title') Templates @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <a href="{{route('templates.create')}}" class="btn btn-dark btn-sm float-right"><i class="fa fa-plus"></i> Template</a>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
    <form class="form-inline mt-3">
        Show &nbsp;
        {{Form::select('s',['all'=>'All','mine'=>'My','country'=>'Country wide','region'=>'Region wide','office'=>'Office wide'],old('selection'),['class'=>'form-control form-control-sm'])}}
        &nbsp; of &nbsp;
        {{Form::select('p',['all'=>'All Time','week'=>'Last Week','month'=>'Last Month','year'=>'Last Year'],old('period'),['class'=>'form-control form-control-sm'])}}
        &nbsp; matching &nbsp;
        <div class="input-group input-group-sm">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <i class="fa fa-search"></i>
                </div>
            </div>
            {{Form::text('q',old('query'),['class'=>'form-control form-control-sm','placeholder'=>'Search...'])}}

        </div>
        <button type="submit" class="btn btn-sm btn-secondary ml-2 mr-2"><i class="fa fa-search"></i> Search</button>
        <a href="{{route('templates.index')}}" class="btn btn-sm btn-info"><i class="fa fa-eraser"></i> Clear</a>
    </form>

    <hr>

    <div class="table-responsive">
        <table class="table table-bordered table-sm table-hover">
            <thead class="btn-dark">
            <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Size</th>
                <th>Uploader</th>
                <th>Added</th>
                <th class="last">Action</th>
            </tr>
            </thead>
            <tbody>
            @forelse($templates as $template)
                <tr>
                    <td><a href="{{route('template',['q'=>$template->file])}}" target="_blank" download="{{$template->name}}.{{$template->type()}}">{{$template->name}}</a></td>
                    <td>{{$template->type()}}</td>
                    <td>{{$template->size()}}</td>
                    <td><a href="{{route('profile',$template->user)}}" title="{{$template->user->name()}}"><img src="{{route('avatar',['q'=>$template->user->avatar])}}" class="blackboard-avatar blackboard-avatar-inline" alt="{{$template->user->name()}}"/></a></td>
                    <td>{{$template->created_at->diffForHumans()}}</td>
                    <td class="last">
                        <a href="{{route('templates.edit',$template)}}" class="btn btn-success btn-sm">Edit</a>
                        {{ Form::open(['method' => 'DELETE','route' => ['templates.destroy', $template],'style'=>'display:inline']) }}
                        <a href="#" class="delete deleteDoc btn btn-danger btn-sm">Delete</a>
                        {{Form::close() }}
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="100%" class="text-center">No templates match those criteria.</td>
                </tr>
            @endforelse
            </tbody>
        </table>
    </div>
    </div>
@endsection